version: '2'
services:
  eureka:
    build: ../microservice-demo/microservice-demo-eureka-server
    ports:
      - "8761:8761"
  customer:
    build: ../microservice-demo/microservice-demo-customer
    links:
     - eureka
    ports:
    - "9002:8080"
#  catalog:
#    build: ../microservice-demo/microservice-demo-catalog
#    links:
#     - eureka
#    ports:
#    - "9000:8080"
  order:
    build: ../microservice-demo/microservice-demo-order
    links:
     - eureka
    ports:
    - "9001:8080"
  zuul:
    build: ../microservice-demo/microservice-demo-zuul-server
    links:
     - eureka
    ports:
      - "8080:8080"
  turbine:
    build: ../microservice-demo/microservice-demo-turbine-server
    links:
     - eureka
    ports:
      - "8989:8989"

#  hub:
#    image: selenium/hub:latest
#    ports:
#      - "4444:4444"
#    expose:
#      - "4444"
#  firefox:
#    image: selenium/node-firefox:latest
#    expose:
#      - "5555"
#    environment:
#     - HUB_PORT_4444_TCP_ADDR=hub
#  chrome:
#    image: selenium/node-chrome:latest
#    expose:
#      - "5555"
#    environment:
#     - HUB_PORT_4444_TCP_ADDR=hub
