---
- hosts: tds
  become: yes

  vars:
    git_url: https://raw.githubusercontent.com/Kalle80/microservice/master/docker/docker-compose.yml
    microservice_home: /etc/microservice
    git_dest: /var/tmp/git

# ansible-galaxy install franklinkim.docker-compose
  roles:
    # - franklinkim.docker
    - franklinkim.docker-compose

  tasks:

  - name: Create Microservice home directory
    file:
      path={{ microservice_home }}
      group=docker
      state=directory mode=0771

  - name: Get docker-compose file from github
    get_url: url={{ git_url }} dest={{ microservice_home }}

  - name: Remove git directory and contents
    file:
      path={{ git_dest }}
      state=absent
  - name: Pull docker images
    command: docker-compose pull chdir={{ microservice_home }}

  - name: Start the docker services
    command: docker-compose -f docker-compose.yml up -d  chdir={{ microservice_home }}
